site_name: Digital Garden
site_url: https://USERNAME.github.io/garden
repo_url: https://github.com/USERNAME/digital-garden
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - content.code.copy
    - search.highlight
    - search.suggest
plugins:
  - search
  - roamlinks   # enables [[wikilinks]]
  - tags        # auto-generate tag index pages
  - awesome-pages
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - md_in_html
nav:
  - Home: index.md
  