name: Deploy MkDocs site

on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build and Deploy
        run: |
          # Build the site
          mkdocs build --strict
          
          # Save built site outside of git working directory
          mv site /tmp/site
          
          # Store current commit message
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          
          # Setup and clean main branch
          if ! git show-ref --verify --quiet refs/remotes/origin/main; then
            git checkout --orphan main
          else
            git checkout main
          fi
          git rm -rf .
          git clean -fxd
          
          # Move built site back into place
          mv /tmp/site/* .
          rm -rf /tmp/site
          
          # Commit and push
          git add .
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Deploy: ${COMMIT_MESSAGE}" || exit 0
          git push origin main