name: Deploy MkDocs site

on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build and Deploy
        run: |
          # Build the site from the checked-out source branch
          mkdocs build --strict

          # Store current commit message for the deployment commit
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          
          # Switch to main, and clean it
          git checkout main
          git rm -rf .
          git clean -fxd
          # Copy the built site from the subdirectory into the root
          cp -r temp_site/* .
          rm -rf temp_site

          # Commit and push
          git add .
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Deploy: ${COMMIT_MESSAGE}" || exit 0
          git push origin main